services:
  gradio-demo:
    build:
      context: .
      dockerfile: Dockerfile.demo
    image: vit-demo:latest
    container_name: vit-demo
    
    ports:
      - "7860:7860"
    
    volumes:
      - ./demos/foodvision_big:/app
      - ./models:/app/models
    
    environment:
      - PYTHONUNBUFFERED=1
    
    stdin_open: true
    tty: true
    
    restart: unless-stopped
